version: "3"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_DISABLE_SSL_VERIFY=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=googleapis
      - N8N_EXTERNAL_MODULES_ALLOWLIST=googleapis
    command: ["n8n"]
    volumes:
      - ~/.n8n:/home/node/.n8n
