version: "3"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_EXTERNAL_MODULES_ALLOWLIST="*"
      - NODE_ENV=production
    volumes:
      - ~/.n8n:/home/node/.n8n
