version: "3"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    user: root
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false  # Tắt SSL Cookie
      - N8N_PROTOCOL=http        # Chạy HTTP thay vì HTTPS
      - N8N_EXTERNAL_MODULES_ALLOWLIST=*
      - N8N_DISABLE_EXTERNAL_MODULES_CHECKS=true
      - N8N_DEFAULT_BINARY_DATA_MODE=default
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_ENV=production
    volumes:
      - ~/.n8n:/home/node/.n8n
