version: "3"

services:
  n8n:
    image: n8nio/n8n
    user: root
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_EXTERNAL_MODULES_ALLOWLIST=googleapis
      - N8N_DISABLE_EXTERNAL_MODULES_CHECKS=true
      - N8N_DEFAULT_BINARY_DATA_MODE=default
      - NODE_ENV=production
    volumes:
      - ~/.n8n:/home/node/.n8n
